apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app        #application name
  labels:
    app: flask-app       #application name
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: flask-app     #application name
  template:
    metadata:
      labels:
        app: flask-app    #application name
    spec:
      containers:
        - name: flask-app      #container name
          image: ghcr.io/toesan-devcloud/my-flask-app:1.0.73
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app  #application service name
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000     #containerPort
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress     #application ingress name
spec:
  ingressClassName: kong
  rules:
    - host: flask.tsandev.org  #domain name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app      #application service name
                port:
                  number: 80
  tls:
    - hosts:
        - flask.tsandev.org      #Domain name
      secretName: tsandev-tls-secret
